version: "3.3"

services:
  db:
    image: postgres
    volumes:
      - cons-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5454:5432

volumes:
  cons-db-data:
