insert into marca (nombre, observacion, pais_id) values ('Chevrolet', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 117);
insert into marca (nombre, observacion, pais_id) values ('Dodge', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 100);
insert into marca (nombre, observacion, pais_id) values ('Oldsmobile', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 70);
insert into marca (nombre, observacion, pais_id) values ('Jeep', 'Quisque ut erat.', 52);
insert into marca (nombre, observacion, pais_id) values ('Lincoln', 'In eleifend quam a odio.', 48);
insert into marca (nombre, observacion, pais_id) values ('Ford', 'Maecenas pulvinar lobortis est.', 63);
insert into marca (nombre, observacion, pais_id) values ('Ford', 'Nam dui.', 120);
insert into marca (nombre, observacion, pais_id) values ('GMC', 'Nulla suscipit ligula in lacus.', 3);
insert into marca (nombre, observacion, pais_id) values ('Mercury', 'Aliquam erat volutpat.', 2);
insert into marca (nombre, observacion, pais_id) values ('Dodge', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 19);
insert into marca (nombre, observacion, pais_id) values ('Chevrolet', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 76);
insert into marca (nombre, observacion, pais_id) values ('Oldsmobile', 'Aenean sit amet justo.', 113);
insert into marca (nombre, observacion, pais_id) values ('Suzuki', 'Quisque porta volutpat erat.', 54);
insert into marca (nombre, observacion, pais_id) values ('Lincoln', 'Nulla tempus.', 86);
insert into marca (nombre, observacion, pais_id) values ('Ford', 'Vivamus in felis eu sapien cursus vestibulum.', 35);
insert into marca (nombre, observacion, pais_id) values ('Volkswagen', 'Donec semper sapien a libero.', 66);
insert into marca (nombre, observacion, pais_id) values ('Chrysler', 'In hac habitasse platea dictumst.', 79);
insert into marca (nombre, observacion, pais_id) values ('GMC', 'Quisque ut erat.', 65);
insert into marca (nombre, observacion, pais_id) values ('Ford', 'In blandit ultrices enim.', 96);
insert into marca (nombre, observacion, pais_id) values ('Pontiac', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 110);
insert into marca (nombre, observacion, pais_id) values ('Mitsubishi', 'Donec dapibus.', 69);
insert into marca (nombre, observacion, pais_id) values ('Chevrolet', 'Nullam porttitor lacus at turpis.', 106);
insert into marca (nombre, observacion, pais_id) values ('MINI', 'Vestibulum sed magna at nunc commodo placerat.', 101);
insert into marca (nombre, observacion, pais_id) values ('Pontiac', 'Vivamus in felis eu sapien cursus vestibulum.', 27);
insert into marca (nombre, observacion, pais_id) values ('Ford', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 63);
insert into marca (nombre, observacion, pais_id) values ('Infiniti', 'Aliquam non mauris.', 73);
insert into marca (nombre, observacion, pais_id) values ('Saturn', 'Duis bibendum.', 5);
insert into marca (nombre, observacion, pais_id) values ('MINI', 'Cras non velit nec nisi vulputate nonummy.', 53);
insert into marca (nombre, observacion, pais_id) values ('Chevrolet', 'Duis at velit eu est congue elementum.', 85);
insert into marca (nombre, observacion, pais_id) values ('GMC', 'Duis aliquam convallis nunc.', 89);
insert into marca (nombre, observacion, pais_id) values ('Land Rover', 'Cras in purus eu magna vulputate luctus.', 113);
insert into marca (nombre, observacion, pais_id) values ('Toyota', 'Integer non velit.', 40);
insert into marca (nombre, observacion, pais_id) values ('Lexus', 'Nullam porttitor lacus at turpis.', 24);
insert into marca (nombre, observacion, pais_id) values ('Mercury', 'In quis justo.', 47);
insert into marca (nombre, observacion, pais_id) values ('Plymouth', 'Morbi porttitor lorem id ligula.', 29);
insert into marca (nombre, observacion, pais_id) values ('Ford', 'Vivamus tortor.', 75);
insert into marca (nombre, observacion, pais_id) values ('Maybach', 'Maecenas rhoncus aliquam lacus.', 29);
insert into marca (nombre, observacion, pais_id) values ('Toyota', 'Nunc nisl.', 69);
insert into marca (nombre, observacion, pais_id) values ('Kia', 'Proin eu mi.', 87);
insert into marca (nombre, observacion, pais_id) values ('Oldsmobile', 'In sagittis dui vel nisl.', 77);
insert into marca (nombre, observacion, pais_id) values ('Ford', 'Integer ac neque.', 100);
insert into marca (nombre, observacion, pais_id) values ('Ford', 'Curabitur gravida nisi at nibh.', 65);
insert into marca (nombre, observacion, pais_id) values ('Lotus', 'Nulla suscipit ligula in lacus.', 15);
insert into marca (nombre, observacion, pais_id) values ('Mazda', 'Nulla ac enim.', 18);
insert into marca (nombre, observacion, pais_id) values ('GMC', 'Nulla mollis molestie lorem.', 39);
insert into marca (nombre, observacion, pais_id) values ('Lexus', 'In hac habitasse platea dictumst.', 10);
insert into marca (nombre, observacion, pais_id) values ('Nissan', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 18);
insert into marca (nombre, observacion, pais_id) values ('Volvo', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 57);
insert into marca (nombre, observacion, pais_id) values ('Dodge', 'Phasellus in felis.', 65);
insert into marca (nombre, observacion, pais_id) values ('Buick', 'Donec ut dolor.', 107);
insert into marca (nombre, observacion, pais_id) values ('Toyota', 'Nunc nisl.', 103);
insert into marca (nombre, observacion, pais_id) values ('Mercury', 'Quisque id justo sit amet sapien dignissim vestibulum.', 123);
insert into marca (nombre, observacion, pais_id) values ('Lexus', 'Aenean fermentum.', 123);
insert into marca (nombre, observacion, pais_id) values ('Ford', 'Donec posuere metus vitae ipsum.', 26);
insert into marca (nombre, observacion, pais_id) values ('Lexus', 'Vivamus in felis eu sapien cursus vestibulum.', 57);
insert into marca (nombre, observacion, pais_id) values ('Bentley', 'Praesent id massa id nisl venenatis lacinia.', 86);
insert into marca (nombre, observacion, pais_id) values ('Chevrolet', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 38);
insert into marca (nombre, observacion, pais_id) values ('Kia', 'Donec posuere metus vitae ipsum.', 33);
insert into marca (nombre, observacion, pais_id) values ('Cadillac', 'Donec vitae nisi.', 3);
insert into marca (nombre, observacion, pais_id) values ('Mitsubishi', 'Donec ut mauris eget massa tempor convallis.', 100);
insert into marca (nombre, observacion, pais_id) values ('Chevrolet', 'Pellentesque at nulla.', 121);
insert into marca (nombre, observacion, pais_id) values ('Land Rover', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 11);
insert into marca (nombre, observacion, pais_id) values ('Mitsubishi', 'Curabitur convallis.', 119);
insert into marca (nombre, observacion, pais_id) values ('Kia', 'Nulla tempus.', 79);
insert into marca (nombre, observacion, pais_id) values ('Maybach', 'In quis justo.', 86);
insert into marca (nombre, observacion, pais_id) values ('Hyundai', 'Mauris ullamcorper purus sit amet nulla.', 73);
insert into marca (nombre, observacion, pais_id) values ('Chevrolet', 'Donec ut mauris eget massa tempor convallis.', 121);
insert into marca (nombre, observacion, pais_id) values ('Lamborghini', 'Duis aliquam convallis nunc.', 115);
insert into marca (nombre, observacion, pais_id) values ('Ford', 'Vivamus vestibulum sagittis sapien.', 77);
insert into marca (nombre, observacion, pais_id) values ('Toyota', 'Integer ac leo.', 13);
insert into marca (nombre, observacion, pais_id) values ('Mitsubishi', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 61);
insert into marca (nombre, observacion, pais_id) values ('Hyundai', 'Donec dapibus.', 67);
insert into marca (nombre, observacion, pais_id) values ('Maybach', 'Aenean lectus.', 105);
insert into marca (nombre, observacion, pais_id) values ('Nissan', 'Suspendisse potenti.', 39);
insert into marca (nombre, observacion, pais_id) values ('BMW', 'Curabitur in libero ut massa volutpat convallis.', 117);
insert into marca (nombre, observacion, pais_id) values ('Mitsubishi', 'Morbi vel lectus in quam fringilla rhoncus.', 54);
insert into marca (nombre, observacion, pais_id) values ('GMC', 'Pellentesque eget nunc.', 5);
insert into marca (nombre, observacion, pais_id) values ('Chevrolet', 'Maecenas ut massa quis augue luctus tincidunt.', 99);
insert into marca (nombre, observacion, pais_id) values ('Toyota', 'Quisque id justo sit amet sapien dignissim vestibulum.', 26);
insert into marca (nombre, observacion, pais_id) values ('Suzuki', 'Proin eu mi.', 111);
insert into marca (nombre, observacion, pais_id) values ('Chevrolet', 'Curabitur gravida nisi at nibh.', 57);
insert into marca (nombre, observacion, pais_id) values ('Volkswagen', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 94);
insert into marca (nombre, observacion, pais_id) values ('Mazda', 'Suspendisse potenti.', 28);
insert into marca (nombre, observacion, pais_id) values ('Nissan', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 105);
insert into marca (nombre, observacion, pais_id) values ('Infiniti', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 9);
insert into marca (nombre, observacion, pais_id) values ('Buick', 'Praesent blandit lacinia erat.', 100);
insert into marca (nombre, observacion, pais_id) values ('Lotus', 'Suspendisse potenti.', 122);
insert into marca (nombre, observacion, pais_id) values ('Nissan', 'Phasellus id sapien in sapien iaculis congue.', 79);
insert into marca (nombre, observacion, pais_id) values ('Volkswagen', 'Etiam vel augue.', 10);
insert into marca (nombre, observacion, pais_id) values ('Isuzu', 'Donec semper sapien a libero.', 4);
insert into marca (nombre, observacion, pais_id) values ('Chevrolet', 'Morbi ut odio.', 122);
insert into marca (nombre, observacion, pais_id) values ('Volkswagen', 'Fusce posuere felis sed lacus.', 25);
insert into marca (nombre, observacion, pais_id) values ('Ford', 'Donec quis orci eget orci vehicula condimentum.', 51);
insert into marca (nombre, observacion, pais_id) values ('Volkswagen', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 101);
insert into marca (nombre, observacion, pais_id) values ('Toyota', 'Suspendisse potenti.', 2);
insert into marca (nombre, observacion, pais_id) values ('Ford', 'Duis consequat dui nec nisi volutpat eleifend.', 121);
insert into marca (nombre, observacion, pais_id) values ('Chevrolet', 'Nullam sit amet turpis elementum ligula vehicula consequat.', 42);
insert into marca (nombre, observacion, pais_id) values ('Chevrolet', 'Morbi quis tortor id nulla ultrices aliquet.', 119);
insert into marca (nombre, observacion, pais_id) values ('Mazda', 'Curabitur at ipsum ac tellus semper interdum.', 89);
insert into marca (nombre, observacion, pais_id) values ('Toyota', 'Vivamus tortor.', 74);
insert into marca (nombre, observacion, pais_id) values ('Pontiac', 'Curabitur gravida nisi at nibh.', 114);
insert into marca (nombre, observacion, pais_id) values ('BMW', 'Aenean sit amet justo.', 38);
insert into marca (nombre, observacion, pais_id) values ('Plymouth', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 69);
insert into marca (nombre, observacion, pais_id) values ('Ford', 'Nulla suscipit ligula in lacus.', 14);
insert into marca (nombre, observacion, pais_id) values ('Mercedes-Benz', 'Nam nulla.', 7);
insert into marca (nombre, observacion, pais_id) values ('Ford', 'Vivamus vestibulum sagittis sapien.', 77);
insert into marca (nombre, observacion, pais_id) values ('Acura', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 54);
insert into marca (nombre, observacion, pais_id) values ('Chevrolet', 'Proin risus.', 67);
insert into marca (nombre, observacion, pais_id) values ('Morgan', 'Vivamus tortor.', 36);
insert into marca (nombre, observacion, pais_id) values ('Volvo', 'Nulla ac enim.', 53);
insert into marca (nombre, observacion, pais_id) values ('Mitsubishi', 'Ut tellus.', 87);
insert into marca (nombre, observacion, pais_id) values ('Land Rover', 'Nullam sit amet turpis elementum ligula vehicula consequat.', 116);
insert into marca (nombre, observacion, pais_id) values ('Lamborghini', 'Donec posuere metus vitae ipsum.', 18);
insert into marca (nombre, observacion, pais_id) values ('Chevrolet', 'Integer ac neque.', 15);
insert into marca (nombre, observacion, pais_id) values ('Acura', 'Vivamus vel nulla eget eros elementum pellentesque.', 13);

insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Cynthy', 'Tomankowski', 'Jabbertype', '34-83678058-2', '419-266-9949', '7202 School Terrace', 'Kasama', 7);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Vernor', 'Marr', 'Quamba', '30-60332431-0', '652-435-3139', '57 Quincy Place', 'Pak Chong', 60);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Cathe', 'Jencken', 'Voonder', '30-08332317-7', '820-485-7670', '969 Arkansas Road', 'Nara', 97);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Ranee', 'Euels', 'Bluezoom', '20-37814066-1', '821-917-6524', '4 Merchant Lane', 'Daniwato', 47);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Keelia', 'Saladino', 'Skippad', '23-87734170-6', '991-502-6697', '95 Bowman Junction', 'Xiaoguwei', 11);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Timmy', 'Matzaitis', 'Quimba', '34-45277920-2', '231-483-0161', '1274 Lawn Alley', 'Ha’erlong', 5);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Eustacia', 'Toderi', 'Feednation', '27-58333078-7', '672-677-0435', '167 Bluejay Drive', 'Al Ghayl', 72);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Friedrick', 'Bramhill', 'Oodoo', '34-88317969-6', '713-786-3640', '76330 Harbort Crossing', 'Bergville', 99);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Consalve', 'Eckford', 'Browsedrive', '34-69050526-9', '323-871-7385', '34 Autumn Leaf Alley', 'Bayeux', 103);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Dirk', 'Cantwell', 'Roomm', '30-06655235-4', '684-181-2048', '3167 Welch Pass', 'Garunggang', 22);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Marika', 'Karlolczak', 'Zoombeat', '34-92093384-2', '254-475-2723', '781 Summit Center', 'Sergach', 119);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Dulciana', 'Claessens', 'Livetube', '34-31143778-5', '978-872-1442', '34425 Hoepker Avenue', 'Xinjie', 39);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Teador', 'Midner', 'Voolia', '34-20320155-9', '938-640-8510', '8 Anhalt Pass', 'Wieniawa', 54);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Corny', 'O''Donovan', 'Pixope', '34-08421245-1', '970-667-9725', '4 Veith Park', 'Tumpang Satu', 62);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Rosaleen', 'Claque', 'Aivee', '30-37086284-4', '254-495-9463', '6 Morning Junction', 'Pulap', 95);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Jacqui', 'Standon', 'Abata', '33-95745502-6', '307-136-5509', '58 Mitchell Way', 'Banqiao', 99);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Katya', 'Yarnley', 'Fatz', '34-74960312-1', '630-243-7431', '582 Autumn Leaf Way', 'São Pedro', 59);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Rennie', 'Jewson', 'Quinu', '34-53589376-4', '680-634-3837', '6 Daystar Street', 'Hengjie', 50);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Krysta', 'Janodet', 'Twiyo', '34-40605802-9', '707-838-1730', '0 Waywood Center', 'Los Pinos', 107);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Symon', 'Jones', 'Thoughtstorm', '30-51758030-6', '554-828-9433', '06967 Longview Drive', 'Fuzihe', 70);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Katalin', 'Edgley', 'Dynabox', '34-05225779-3', '368-971-7458', '26087 Mcguire Center', 'Bakalang', 78);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Benedick', 'Dentith', 'Skajo', '23-50253837-6', '481-567-7593', '88 Mendota Plaza', 'Chust Shahri', 97);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Florentia', 'Botger', 'Ainyx', '33-84206977-1', '498-956-4278', '05 Anniversary Center', 'Zhonghekou', 2);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Massimiliano', 'Jedrzejczyk', 'Trupe', '23-69578102-1', '248-797-0089', '67203 Prairie Rose Pass', 'Sobradinho', 109);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Huntlee', 'Malpass', 'Einti', '34-50431863-9', '240-951-5527', '5 Sundown Place', 'Miatli', 121);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Ursulina', 'Gillbee', 'Ainyx', '34-44815968-9', '232-302-4133', '0 Nancy Trail', 'Saint Aubin', 87);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Nelson', 'Clapperton', 'Oyope', '34-18274910-8', '732-496-4874', '04157 Transport Park', 'Majingklak', 58);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Miller', 'Kent', 'Kwideo', '34-35382070-4', '296-841-8148', '1236 Victoria Place', 'Tambakrejo', 38);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Dirk', 'Scambler', 'Avamba', '33-10359447-1', '152-828-9568', '0808 Pierstorff Point', 'Guashe', 122);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Ada', 'Bretherton', 'Skippad', '34-48412339-0', '311-666-4788', '2 Fairfield Drive', 'Suibara', 51);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Rhoda', 'Carlton', 'Oyonder', '33-67546943-0', '827-180-6161', '32 Charing Cross Court', 'Encontrados', 73);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Alleyn', 'Josskowitz', 'Cogibox', '27-61123313-6', '588-299-8877', '0 Sachtjen Place', 'Likupang', 71);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Mae', 'Johnsey', 'Demivee', '34-66629326-3', '588-808-2795', '453 Elka Hill', 'Cagdianao', 79);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Rance', 'Orth', 'Ozu', '34-84269548-0', '609-405-8894', '72 Redwing Crossing', 'Cisarap', 27);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Asia', 'Harsent', 'Yambee', '34-45128902-3', '255-100-8848', '1118 Continental Hill', 'Jiangcun', 72);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Noell', 'Grishagin', 'Roombo', '27-61034405-6', '679-282-6029', '6560 Kennedy Crossing', 'Irricana', 104);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Fernande', 'Hackey', 'Quinu', '33-00568449-0', '442-991-8150', '3514 Roth Way', 'Dolní Bojanovice', 52);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Gerik', 'Penny', 'Agivu', '20-00689267-3', '759-968-9345', '6534 Bluestem Trail', 'Janeng', 72);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Chane', 'Rous', 'Linkbridge', '33-67153490-0', '704-175-3118', '8 Weeping Birch Parkway', 'Le Teil', 44);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Archie', 'McCafferky', 'Rooxo', '34-22368775-9', '538-252-4155', '42 Hauk Junction', 'Al Jafr', 96);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Viviana', 'Wastling', 'Rhycero', '34-86663415-3', '981-473-4875', '872 Hoepker Park', 'Plateliai', 81);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Ivett', 'Tetla', 'Blogtags', '34-29746724-6', '137-511-1055', '4667 Fremont Lane', 'Taipa', 116);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Cthrine', 'Morgen', 'Feedspan', '20-56479494-0', '355-958-7031', '4 Everett Point', 'Jianling', 114);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Stephen', 'Mossdale', 'Dynabox', '27-42529594-1', '831-589-7868', '2 Banding Trail', 'Ogaminan', 74);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Hadlee', 'Lefwich', 'Gigazoom', '33-77213890-8', '809-417-7688', '15353 Del Mar Park', 'Mocímboa', 52);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Nicoli', 'Druery', 'Innotype', '27-03708250-9', '466-526-5341', '83628 Esker Court', 'Halmstad', 66);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Alberto', 'Seville', 'Yata', '34-75152081-6', '678-242-4038', '59361 Elmside Center', 'Šardice', 97);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Elane', 'Mac Giolla Pheadair', 'Brainlounge', '33-92994741-2', '892-267-3322', '31132 Oak Circle', 'Douba', 95);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Josepha', 'Salery', 'Twitterbridge', '33-77975611-9', '649-161-4383', '64672 Lawn Center', 'Ichuña', 39);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Dotti', 'De Maria', 'Jatri', '34-87104976-1', '582-570-4118', '116 Northwestern Terrace', 'Tajike’abati', 91);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Britte', 'Headings', 'Skalith', '33-64175705-0', '754-857-2321', '85 Iowa Park', 'Canguaretama', 52);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Dulcia', 'Korf', 'Skiba', '34-13632888-0', '983-999-3219', '6 Cascade Drive', 'Gading', 1);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Torey', 'Surman-Wells', 'Cogibox', '27-11995047-1', '669-632-7983', '1874 Ludington Drive', 'Avignon', 2);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Robena', 'Gaspard', 'Skimia', '34-73437380-1', '300-301-8384', '50 Havey Plaza', 'Destrnik', 107);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Staffard', 'Probat', 'Mydeo', '34-36734716-3', '280-193-5384', '08 Alpine Street', 'Belogorskīy', 104);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Amitie', 'Cartman', 'Skalith', '33-53843376-3', '888-945-8107', '327 Scott Court', 'Kasba Tadla', 49);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Francyne', 'Scholling', 'Livefish', '23-67484706-1', '360-169-3356', '55722 Tennyson Parkway', 'Sepīdān', 91);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Odie', 'Hargreves', 'Livetube', '23-22320487-7', '696-254-3288', '3971 Prentice Circle', 'Pop', 46);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Gwenny', 'Thomson', 'Gabtune', '27-13340895-9', '668-110-2388', '87 Merchant Lane', 'Tumpukrenteng', 115);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Gus', 'Pitkin', 'Thoughtblab', '30-57345921-1', '158-192-0307', '4 Knutson Drive', 'Ludza', 112);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Decca', 'Di Carli', 'Roodel', '23-64915843-1', '736-730-7604', '27114 Elmside Way', 'Nakonde', 54);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Hailey', 'Dat', 'Skimia', '33-15633666-1', '104-764-5704', '36439 Oakridge Street', 'Áno Kalentíni', 113);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Kaylil', 'Stanyforth', 'Wordpedia', '33-67650093-0', '194-181-6739', '0148 Anthes Court', 'Thới Bình', 66);
insert into cliente (nombre, apellido, razon_social, CUIT, telefono, direccion, localidad, pais_id) values ('Georgina', 'Mainstone', 'Riffpedia', '34-76642411-3', '862-754-8786', '3687 Delaware Plaza', 'Pyshchug', 116);

insert into modelo (nombre, anio, marca_id) values ('Amigo', 2000, 182);
insert into modelo (nombre, anio, marca_id) values ('E-Class', 1988, 412);
insert into modelo (nombre, anio, marca_id) values ('Explorer', 1995, 439);
insert into modelo (nombre, anio, marca_id) values ('Escort', 1998, 482);
insert into modelo (nombre, anio, marca_id) values ('MR2', 1985, 375);
insert into modelo (nombre, anio, marca_id) values ('Celica', 2003, 263);
insert into modelo (nombre, anio, marca_id) values ('Ram Van 1500', 2001, 243);
insert into modelo (nombre, anio, marca_id) values ('XC70', 2010, 98);
insert into modelo (nombre, anio, marca_id) values ('A8', 2007, 347);
insert into modelo (nombre, anio, marca_id) values ('Suburban 1500', 1993, 223);
insert into modelo (nombre, anio, marca_id) values ('RL', 2004, 165);
insert into modelo (nombre, anio, marca_id) values ('S-Type', 2001, 5);
insert into modelo (nombre, anio, marca_id) values ('Leone', 1988, 182);
insert into modelo (nombre, anio, marca_id) values ('Aztek', 2005, 356);
insert into modelo (nombre, anio, marca_id) values ('Cooper', 2011, 173);
insert into modelo (nombre, anio, marca_id) values ('Sierra 2500', 2005, 461);
insert into modelo (nombre, anio, marca_id) values ('Caravan', 2000, 454);
insert into modelo (nombre, anio, marca_id) values ('S80', 2010, 230);
insert into modelo (nombre, anio, marca_id) values ('Corolla', 2000, 113);
insert into modelo (nombre, anio, marca_id) values ('A4', 2002, 398);
insert into modelo (nombre, anio, marca_id) values ('Maxima', 1993, 352);
insert into modelo (nombre, anio, marca_id) values ('Swift', 1996, 132);
insert into modelo (nombre, anio, marca_id) values ('Silverado 3500HD', 2006, 136);
insert into modelo (nombre, anio, marca_id) values ('Regency', 1998, 394);
insert into modelo (nombre, anio, marca_id) values ('Miata MX-5', 2004, 343);
insert into modelo (nombre, anio, marca_id) values ('Navigator', 2009, 409);
insert into modelo (nombre, anio, marca_id) values ('Eos', 2010, 425);
insert into modelo (nombre, anio, marca_id) values ('Sportvan G20', 1995, 437);
insert into modelo (nombre, anio, marca_id) values ('F150', 1998, 47);
insert into modelo (nombre, anio, marca_id) values ('Q', 1996, 100);
insert into modelo (nombre, anio, marca_id) values ('LHS', 2000, 77);
insert into modelo (nombre, anio, marca_id) values ('Park Avenue', 2001, 386);
insert into modelo (nombre, anio, marca_id) values ('Continental Flying Spur', 2011, 17);
insert into modelo (nombre, anio, marca_id) values ('Avalanche 2500', 2005, 439);
insert into modelo (nombre, anio, marca_id) values ('Ion', 2004, 31);
insert into modelo (nombre, anio, marca_id) values ('Z4', 2010, 282);
insert into modelo (nombre, anio, marca_id) values ('Mustang', 1985, 107);
insert into modelo (nombre, anio, marca_id) values ('Touareg', 2003, 396);
insert into modelo (nombre, anio, marca_id) values ('200SX', 1996, 374);
insert into modelo (nombre, anio, marca_id) values ('Elantra', 1992, 55);
insert into modelo (nombre, anio, marca_id) values ('Shadow', 1992, 163);
insert into modelo (nombre, anio, marca_id) values ('Rodeo', 2000, 278);
insert into modelo (nombre, anio, marca_id) values ('MR2', 1993, 458);
insert into modelo (nombre, anio, marca_id) values ('Silverado', 2007, 392);
insert into modelo (nombre, anio, marca_id) values ('Thunderbird', 2005, 424);
insert into modelo (nombre, anio, marca_id) values ('QX', 1998, 498);
insert into modelo (nombre, anio, marca_id) values ('Ridgeline', 2011, 21);
insert into modelo (nombre, anio, marca_id) values ('Accent', 2005, 384);
insert into modelo (nombre, anio, marca_id) values ('F-Series', 2006, 308);
insert into modelo (nombre, anio, marca_id) values ('LeSabre', 1985, 47);
insert into modelo (nombre, anio, marca_id) values ('SM', 1972, 453);
insert into modelo (nombre, anio, marca_id) values ('Insight', 2004, 23);
insert into modelo (nombre, anio, marca_id) values ('911', 1993, 86);
insert into modelo (nombre, anio, marca_id) values ('SL-Class', 2004, 107);
insert into modelo (nombre, anio, marca_id) values ('57', 2008, 256);
insert into modelo (nombre, anio, marca_id) values ('Grand Voyager', 1992, 203);
insert into modelo (nombre, anio, marca_id) values ('Esprit', 1999, 57);
insert into modelo (nombre, anio, marca_id) values ('Tacoma Xtra', 2004, 455);
insert into modelo (nombre, anio, marca_id) values ('G37', 2011, 177);
insert into modelo (nombre, anio, marca_id) values ('SLK55 AMG', 2009, 468);
insert into modelo (nombre, anio, marca_id) values ('GS', 2011, 349);
insert into modelo (nombre, anio, marca_id) values ('Sonata', 2011, 43);
insert into modelo (nombre, anio, marca_id) values ('Escape', 2008, 371);
insert into modelo (nombre, anio, marca_id) values ('Passat', 2009, 41);
insert into modelo (nombre, anio, marca_id) values ('Commander', 2008, 148);
insert into modelo (nombre, anio, marca_id) values ('C8 Spyder', 2004, 3);
insert into modelo (nombre, anio, marca_id) values ('Festiva', 1992, 379);
insert into modelo (nombre, anio, marca_id) values ('Neon', 1995, 368);
insert into modelo (nombre, anio, marca_id) values ('CLK-Class', 2008, 250);
insert into modelo (nombre, anio, marca_id) values ('Expedition', 2012, 157);
insert into modelo (nombre, anio, marca_id) values ('Grand Vitara', 2008, 101);
insert into modelo (nombre, anio, marca_id) values ('Continental', 2005, 470);
insert into modelo (nombre, anio, marca_id) values ('911', 2003, 141);
insert into modelo (nombre, anio, marca_id) values ('MKX', 2012, 118);
insert into modelo (nombre, anio, marca_id) values ('Thunderbird', 1995, 151);
insert into modelo (nombre, anio, marca_id) values ('GS', 2011, 300);
insert into modelo (nombre, anio, marca_id) values ('Charger', 1999, 179);
insert into modelo (nombre, anio, marca_id) values ('F150', 1997, 17);
insert into modelo (nombre, anio, marca_id) values ('MPV', 1993, 417);
insert into modelo (nombre, anio, marca_id) values ('Azure', 2009, 30);
insert into modelo (nombre, anio, marca_id) values ('Cabriolet', 1992, 318);
insert into modelo (nombre, anio, marca_id) values ('Ram Van 1500', 2002, 332);
insert into modelo (nombre, anio, marca_id) values ('968', 1995, 55);
insert into modelo (nombre, anio, marca_id) values ('Silhouette', 1998, 270);
insert into modelo (nombre, anio, marca_id) values ('Sonoma', 1992, 237);
insert into modelo (nombre, anio, marca_id) values ('MX-3', 1996, 497);
insert into modelo (nombre, anio, marca_id) values ('F250', 2003, 221);
insert into modelo (nombre, anio, marca_id) values ('Bonneville', 1967, 336);
insert into modelo (nombre, anio, marca_id) values ('Fleetwood', 1992, 313);
insert into modelo (nombre, anio, marca_id) values ('G-Series G10', 1992, 229);
insert into modelo (nombre, anio, marca_id) values ('Outlook', 2010, 224);
insert into modelo (nombre, anio, marca_id) values ('3000GT', 1999, 382);
insert into modelo (nombre, anio, marca_id) values ('Accent', 2000, 453);
