insert into region (id, nombre) values (1, 'Sudamerica');

insert into pais (nombre, codigo, region_id) values ('Bolivia', 'BO', 1);
insert into pais (nombre, codigo, region_id) values ('Brazil', 'BR', 1);
insert into pais (nombre, codigo, region_id) values ('Chile', 'CL', 1);
insert into pais (nombre, codigo, region_id) values ('Colombia', 'CO', 1);
insert into pais (nombre, codigo, region_id) values ('Ecuador', 'EC', 1);
insert into pais (nombre, codigo, region_id) values ('Paraguay', 'PY', 1);
insert into pais (nombre, codigo, region_id) values ('Peru', 'PE', 1);
insert into pais (nombre, codigo, region_id) values ('Uruguay', 'UY', 1);
insert into pais (nombre, codigo, region_id) values ('Venezuela', 'VE', 1);

-- ########################################################################### --

insert into region (id, nombre) values (2, 'Extrangero');

insert into pais (nombre, codigo, region_id) values ('Afghanistan', 'AF', 2);
insert into pais (nombre, codigo, region_id) values ('Aland Islands', 'AX', 2);
insert into pais (nombre, codigo, region_id) values ('Albania', 'AL', 2);
insert into pais (nombre, codigo, region_id) values ('Angola', 'AO', 2);
insert into pais (nombre, codigo, region_id) values ('Armenia', 'AM', 2);
insert into pais (nombre, codigo, region_id) values ('Azerbaijan', 'AZ', 2);
insert into pais (nombre, codigo, region_id) values ('Bahrain', 'BH', 2);
insert into pais (nombre, codigo, region_id) values ('Bangladesh', 'BD', 2);
insert into pais (nombre, codigo, region_id) values ('Barbados', 'BB', 2);
insert into pais (nombre, codigo, region_id) values ('Belarus', 'BY', 2);
insert into pais (nombre, codigo, region_id) values ('Belgium', 'BE', 2);
insert into pais (nombre, codigo, region_id) values ('Bosnia and Herzegovina', 'BA', 2);
insert into pais (nombre, codigo, region_id) values ('Botswana', 'BW', 2);
insert into pais (nombre, codigo, region_id) values ('Burkina Faso', 'BF', 2);
insert into pais (nombre, codigo, region_id) values ('Cambodia', 'KH', 2);
insert into pais (nombre, codigo, region_id) values ('Cameroon', 'CM', 2);
insert into pais (nombre, codigo, region_id) values ('Canada', 'CA', 2);
insert into pais (nombre, codigo, region_id) values ('Cape Verde', 'CV', 2);
insert into pais (nombre, codigo, region_id) values ('Chad', 'TD', 2);
insert into pais (nombre, codigo, region_id) values ('China', 'CN', 2);
insert into pais (nombre, codigo, region_id) values ('Croatia', 'HR', 2);
insert into pais (nombre, codigo, region_id) values ('Cuba', 'CU', 2);
insert into pais (nombre, codigo, region_id) values ('Czech Republic', 'CZ', 2);
insert into pais (nombre, codigo, region_id) values ('Democratic Republic of the Congo', 'CD', 2);
insert into pais (nombre, codigo, region_id) values ('Denmark', 'DK', 2);
insert into pais (nombre, codigo, region_id) values ('Dominica', 'DM', 2);
insert into pais (nombre, codigo, region_id) values ('Dominican Republic', 'DO', 2);
insert into pais (nombre, codigo, region_id) values ('East Timor', 'TL', 2);
insert into pais (nombre, codigo, region_id) values ('Egypt', 'EG', 2);
insert into pais (nombre, codigo, region_id) values ('El Salvador', 'SV', 2);
insert into pais (nombre, codigo, region_id) values ('Estonia', 'EE', 2);
insert into pais (nombre, codigo, region_id) values ('Ethiopia', 'ET', 2);
insert into pais (nombre, codigo, region_id) values ('Finland', 'FI', 2);
insert into pais (nombre, codigo, region_id) values ('France', 'FR', 2);
insert into pais (nombre, codigo, region_id) values ('Gambia', 'GM', 2);
insert into pais (nombre, codigo, region_id) values ('Georgia', 'GE', 2);
insert into pais (nombre, codigo, region_id) values ('Germany', 'DE', 2);
insert into pais (nombre, codigo, region_id) values ('Ghana', 'GH', 2);
insert into pais (nombre, codigo, region_id) values ('Greece', 'GR', 2);
insert into pais (nombre, codigo, region_id) values ('Grenada', 'GD', 2);
insert into pais (nombre, codigo, region_id) values ('Guatemala', 'GT', 2);
insert into pais (nombre, codigo, region_id) values ('Haiti', 'HT', 2);
insert into pais (nombre, codigo, region_id) values ('Honduras', 'HN', 2);
insert into pais (nombre, codigo, region_id) values ('Indonesia', 'ID', 2);
insert into pais (nombre, codigo, region_id) values ('Iran', 'IR', 2);
insert into pais (nombre, codigo, region_id) values ('Iraq', 'IQ', 2);
insert into pais (nombre, codigo, region_id) values ('Ireland', 'IE', 2);
insert into pais (nombre, codigo, region_id) values ('Israel', 'IL', 2);
insert into pais (nombre, codigo, region_id) values ('Italy', 'IT', 2);
insert into pais (nombre, codigo, region_id) values ('Ivory Coast', 'CI', 2);
insert into pais (nombre, codigo, region_id) values ('Japan', 'JP', 2);
insert into pais (nombre, codigo, region_id) values ('Kazakhstan', 'KZ', 2);
insert into pais (nombre, codigo, region_id) values ('Laos', 'LA', 2);
insert into pais (nombre, codigo, region_id) values ('Lesotho', 'LS', 2);
insert into pais (nombre, codigo, region_id) values ('Liberia', 'LR', 2);
insert into pais (nombre, codigo, region_id) values ('Libya', 'LY', 2);
insert into pais (nombre, codigo, region_id) values ('Lithuania', 'LT', 2);
insert into pais (nombre, codigo, region_id) values ('Luxembourg', 'LU', 2);
insert into pais (nombre, codigo, region_id) values ('Macedonia', 'MK', 2);
insert into pais (nombre, codigo, region_id) values ('Madagascar', 'MG', 2);
insert into pais (nombre, codigo, region_id) values ('Malawi', 'MW', 2);
insert into pais (nombre, codigo, region_id) values ('Malaysia', 'MY', 2);
insert into pais (nombre, codigo, region_id) values ('Malta', 'MT', 2);
insert into pais (nombre, codigo, region_id) values ('Marshall Islands', 'MH', 2);
insert into pais (nombre, codigo, region_id) values ('Mauritania', 'MR', 2);
insert into pais (nombre, codigo, region_id) values ('Mexico', 'MX', 2);
insert into pais (nombre, codigo, region_id) values ('Micronesia', 'FM', 2);
insert into pais (nombre, codigo, region_id) values ('Mongolia', 'MN', 2);
insert into pais (nombre, codigo, region_id) values ('Montenegro', 'ME', 2);
insert into pais (nombre, codigo, region_id) values ('Morocco', 'MA', 2);
insert into pais (nombre, codigo, region_id) values ('Myanmar', 'MM', 2);
insert into pais (nombre, codigo, region_id) values ('Namibia', 'NA', 2);
insert into pais (nombre, codigo, region_id) values ('Nepal', 'NP', 2);
insert into pais (nombre, codigo, region_id) values ('Netherlands', 'NL', 2);
insert into pais (nombre, codigo, region_id) values ('Nicaragua', 'NI', 2);
insert into pais (nombre, codigo, region_id) values ('Nigeria', 'NG', 2);
insert into pais (nombre, codigo, region_id) values ('Norfolk Island', 'NF', 2);
insert into pais (nombre, codigo, region_id) values ('Norway', 'NO', 2);
insert into pais (nombre, codigo, region_id) values ('Pakistan', 'PK', 2);
insert into pais (nombre, codigo, region_id) values ('Palestinian Territory', 'PS', 2);
insert into pais (nombre, codigo, region_id) values ('Panama', 'PA', 2);
insert into pais (nombre, codigo, region_id) values ('Papua New Guinea', 'PG', 2);
insert into pais (nombre, codigo, region_id) values ('Philippines', 'PH', 2);
insert into pais (nombre, codigo, region_id) values ('Poland', 'PL', 2);
insert into pais (nombre, codigo, region_id) values ('Portugal', 'PT', 2);
insert into pais (nombre, codigo, region_id) values ('Reunion', 'RE', 2);
insert into pais (nombre, codigo, region_id) values ('Russia', 'RU', 2);
insert into pais (nombre, codigo, region_id) values ('Saint Kitts and Nevis', 'KN', 2);
insert into pais (nombre, codigo, region_id) values ('Serbia', 'RS', 2);
insert into pais (nombre, codigo, region_id) values ('Sierra Leone', 'SL', 2);
insert into pais (nombre, codigo, region_id) values ('Somalia', 'SO', 2);
insert into pais (nombre, codigo, region_id) values ('South Africa', 'ZA', 2);
insert into pais (nombre, codigo, region_id) values ('South Korea', 'KR', 2);
insert into pais (nombre, codigo, region_id) values ('Spain', 'ES', 2);
insert into pais (nombre, codigo, region_id) values ('Sri Lanka', 'LK', 2);
insert into pais (nombre, codigo, region_id) values ('Sweden', 'SE', 2);
insert into pais (nombre, codigo, region_id) values ('Syria', 'SY', 2);
insert into pais (nombre, codigo, region_id) values ('Tajikistan', 'TJ', 2);
insert into pais (nombre, codigo, region_id) values ('Tanzania', 'TZ', 2);
insert into pais (nombre, codigo, region_id) values ('Thailand', 'TH', 2);
insert into pais (nombre, codigo, region_id) values ('Trinidad and Tobago', 'TT', 2);
insert into pais (nombre, codigo, region_id) values ('Tunisia', 'TN', 2);
insert into pais (nombre, codigo, region_id) values ('U.S. Virgin Islands', 'VI', 2);
insert into pais (nombre, codigo, region_id) values ('Uganda', 'UG', 2);
insert into pais (nombre, codigo, region_id) values ('Ukraine', 'UA', 2);
insert into pais (nombre, codigo, region_id) values ('United Kingdom', 'GB', 2);
insert into pais (nombre, codigo, region_id) values ('United States', 'US', 2);
insert into pais (nombre, codigo, region_id) values ('Uzbekistan', 'UZ', 2);
insert into pais (nombre, codigo, region_id) values ('Vietnam', 'VN', 2);
insert into pais (nombre, codigo, region_id) values ('Wallis and Futuna', 'WF', 2);
insert into pais (nombre, codigo, region_id) values ('Yemen', 'YE', 2);
insert into pais (nombre, codigo, region_id) values ('Zambia', 'ZM', 2);
insert into pais (nombre, codigo, region_id) values ('Zimbabwe', 'ZW', 2);

-- ########################################################################### --

insert into region (id, nombre) values (3, 'Local');

insert into pais (nombre, codigo, region_id) values ('Argentina', 'AR', 3);
