insert into pais (nombre, codigo) values ('Afghanistan', 'AF');
insert into pais (nombre, codigo) values ('Aland Islands', 'AX');
insert into pais (nombre, codigo) values ('Albania', 'AL');
insert into pais (nombre, codigo) values ('Angola', 'AO');
insert into pais (nombre, codigo) values ('Argentina', 'AR');
insert into pais (nombre, codigo) values ('Armenia', 'AM');
insert into pais (nombre, codigo) values ('Azerbaijan', 'AZ');
insert into pais (nombre, codigo) values ('Bahrain', 'BH');
insert into pais (nombre, codigo) values ('Bangladesh', 'BD');
insert into pais (nombre, codigo) values ('Barbados', 'BB');
insert into pais (nombre, codigo) values ('Belarus', 'BY');
insert into pais (nombre, codigo) values ('Belgium', 'BE');
insert into pais (nombre, codigo) values ('Bolivia', 'BO');
insert into pais (nombre, codigo) values ('Bosnia and Herzegovina', 'BA');
insert into pais (nombre, codigo) values ('Botswana', 'BW');
insert into pais (nombre, codigo) values ('Brazil', 'BR');
insert into pais (nombre, codigo) values ('Burkina Faso', 'BF');
insert into pais (nombre, codigo) values ('Cambodia', 'KH');
insert into pais (nombre, codigo) values ('Cameroon', 'CM');
insert into pais (nombre, codigo) values ('Canada', 'CA');
insert into pais (nombre, codigo) values ('Cape Verde', 'CV');
insert into pais (nombre, codigo) values ('Chad', 'TD');
insert into pais (nombre, codigo) values ('Chile', 'CL');
insert into pais (nombre, codigo) values ('China', 'CN');
insert into pais (nombre, codigo) values ('Colombia', 'CO');
insert into pais (nombre, codigo) values ('Croatia', 'HR');
insert into pais (nombre, codigo) values ('Cuba', 'CU');
insert into pais (nombre, codigo) values ('Czech Republic', 'CZ');
insert into pais (nombre, codigo) values ('Democratic Republic of the Congo', 'CD');
insert into pais (nombre, codigo) values ('Denmark', 'DK');
insert into pais (nombre, codigo) values ('Dominica', 'DM');
insert into pais (nombre, codigo) values ('Dominican Republic', 'DO');
insert into pais (nombre, codigo) values ('East Timor', 'TL');
insert into pais (nombre, codigo) values ('Ecuador', 'EC');
insert into pais (nombre, codigo) values ('Egypt', 'EG');
insert into pais (nombre, codigo) values ('El Salvador', 'SV');
insert into pais (nombre, codigo) values ('Estonia', 'EE');
insert into pais (nombre, codigo) values ('Ethiopia', 'ET');
insert into pais (nombre, codigo) values ('Finland', 'FI');
insert into pais (nombre, codigo) values ('France', 'FR');
insert into pais (nombre, codigo) values ('Gambia', 'GM');
insert into pais (nombre, codigo) values ('Georgia', 'GE');
insert into pais (nombre, codigo) values ('Germany', 'DE');
insert into pais (nombre, codigo) values ('Ghana', 'GH');
insert into pais (nombre, codigo) values ('Greece', 'GR');
insert into pais (nombre, codigo) values ('Grenada', 'GD');
insert into pais (nombre, codigo) values ('Guatemala', 'GT');
insert into pais (nombre, codigo) values ('Haiti', 'HT');
insert into pais (nombre, codigo) values ('Honduras', 'HN');
insert into pais (nombre, codigo) values ('Indonesia', 'ID');
insert into pais (nombre, codigo) values ('Iran', 'IR');
insert into pais (nombre, codigo) values ('Iraq', 'IQ');
insert into pais (nombre, codigo) values ('Ireland', 'IE');
insert into pais (nombre, codigo) values ('Israel', 'IL');
insert into pais (nombre, codigo) values ('Italy', 'IT');
insert into pais (nombre, codigo) values ('Ivory Coast', 'CI');
insert into pais (nombre, codigo) values ('Japan', 'JP');
insert into pais (nombre, codigo) values ('Kazakhstan', 'KZ');
insert into pais (nombre, codigo) values ('Laos', 'LA');
insert into pais (nombre, codigo) values ('Lesotho', 'LS');
insert into pais (nombre, codigo) values ('Liberia', 'LR');
insert into pais (nombre, codigo) values ('Libya', 'LY');
insert into pais (nombre, codigo) values ('Lithuania', 'LT');
insert into pais (nombre, codigo) values ('Luxembourg', 'LU');
insert into pais (nombre, codigo) values ('Macedonia', 'MK');
insert into pais (nombre, codigo) values ('Madagascar', 'MG');
insert into pais (nombre, codigo) values ('Malawi', 'MW');
insert into pais (nombre, codigo) values ('Malaysia', 'MY');
insert into pais (nombre, codigo) values ('Malta', 'MT');
insert into pais (nombre, codigo) values ('Marshall Islands', 'MH');
insert into pais (nombre, codigo) values ('Mauritania', 'MR');
insert into pais (nombre, codigo) values ('Mexico', 'MX');
insert into pais (nombre, codigo) values ('Micronesia', 'FM');
insert into pais (nombre, codigo) values ('Mongolia', 'MN');
insert into pais (nombre, codigo) values ('Montenegro', 'ME');
insert into pais (nombre, codigo) values ('Morocco', 'MA');
insert into pais (nombre, codigo) values ('Myanmar', 'MM');
insert into pais (nombre, codigo) values ('Namibia', 'NA');
insert into pais (nombre, codigo) values ('Nepal', 'NP');
insert into pais (nombre, codigo) values ('Netherlands', 'NL');
insert into pais (nombre, codigo) values ('Nicaragua', 'NI');
insert into pais (nombre, codigo) values ('Nigeria', 'NG');
insert into pais (nombre, codigo) values ('Norfolk Island', 'NF');
insert into pais (nombre, codigo) values ('Norway', 'NO');
insert into pais (nombre, codigo) values ('Pakistan', 'PK');
insert into pais (nombre, codigo) values ('Palestinian Territory', 'PS');
insert into pais (nombre, codigo) values ('Panama', 'PA');
insert into pais (nombre, codigo) values ('Papua New Guinea', 'PG');
insert into pais (nombre, codigo) values ('Paraguay', 'PY');
insert into pais (nombre, codigo) values ('Peru', 'PE');
insert into pais (nombre, codigo) values ('Philippines', 'PH');
insert into pais (nombre, codigo) values ('Poland', 'PL');
insert into pais (nombre, codigo) values ('Portugal', 'PT');
insert into pais (nombre, codigo) values ('Reunion', 'RE');
insert into pais (nombre, codigo) values ('Russia', 'RU');
insert into pais (nombre, codigo) values ('Saint Kitts and Nevis', 'KN');
insert into pais (nombre, codigo) values ('Serbia', 'RS');
insert into pais (nombre, codigo) values ('Sierra Leone', 'SL');
insert into pais (nombre, codigo) values ('Somalia', 'SO');
insert into pais (nombre, codigo) values ('South Africa', 'ZA');
insert into pais (nombre, codigo) values ('South Korea', 'KR');
insert into pais (nombre, codigo) values ('Spain', 'ES');
insert into pais (nombre, codigo) values ('Sri Lanka', 'LK');
insert into pais (nombre, codigo) values ('Sweden', 'SE');
insert into pais (nombre, codigo) values ('Syria', 'SY');
insert into pais (nombre, codigo) values ('Tajikistan', 'TJ');
insert into pais (nombre, codigo) values ('Tanzania', 'TZ');
insert into pais (nombre, codigo) values ('Thailand', 'TH');
insert into pais (nombre, codigo) values ('Trinidad and Tobago', 'TT');
insert into pais (nombre, codigo) values ('Tunisia', 'TN');
insert into pais (nombre, codigo) values ('U.S. Virgin Islands', 'VI');
insert into pais (nombre, codigo) values ('Uganda', 'UG');
insert into pais (nombre, codigo) values ('Ukraine', 'UA');
insert into pais (nombre, codigo) values ('United Kingdom', 'GB');
insert into pais (nombre, codigo) values ('United States', 'US');
insert into pais (nombre, codigo) values ('Uruguay', 'UY');
insert into pais (nombre, codigo) values ('Uzbekistan', 'UZ');
insert into pais (nombre, codigo) values ('Venezuela', 'VE');
insert into pais (nombre, codigo) values ('Vietnam', 'VN');
insert into pais (nombre, codigo) values ('Wallis and Futuna', 'WF');
insert into pais (nombre, codigo) values ('Yemen', 'YE');
insert into pais (nombre, codigo) values ('Zambia', 'ZM');
insert into pais (nombre, codigo) values ('Zimbabwe', 'ZW');
